[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel", "numpy"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-vvv"
testpaths = [
    "test"
]
